In [1]:
import torch

张量表示一个数值组成的数组，有很多维度

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [5]:
x.numel()
# number of element

12

In [6]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
torch.tensor([[2,1,4,3],[2,3,1,5],[1,2,3,4]])
# 嵌套数组

tensor([[2, 1, 4, 3],
        [2, 3, 1, 5],
        [1, 2, 3, 4]])

In [10]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y
# 按元素运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [12]:
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)
# 按行拼接，按列拼接
# reshape在原来基础上操作

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [13]:
# 逻辑运算 ：元素
x==y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [14]:
# 求和
x.sum()

tensor(66.)

In [15]:
# 广播机制
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [16]:
a+b #a会复制成两列，b会复制成三行

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [17]:
x[-1],x[1:3]
# 行

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [18]:
x[1,2] = 9
x #写入

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [19]:
x[0:2,:] =12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [20]:
# 内存问题
before = id(y)
y =y +x
id(y) ==before  # id理解为指针
# 最好不要不断赋值

False

In [23]:
# 原地操作
z = torch.zeros_like(y)
print('id(z):',id(z))
z[:] = x+y  # 元素改写，不是赋值
print('id(z):',id(z))
before = id(x)
x+=y  # 没用重复使用x也可
id(x) == before

id(z): 1733316021344
id(z): 1733316021344


True

In [24]:
# 转换为numpy
A= x.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [25]:
# 标量
a = torch.tensor([1.0])
a,a.item(),float(a),int(a)

(tensor([1.]), 1.0, 1.0, 1)

In [27]:
import os

os.makedirs(os.path.join('../','data'),exist_ok=True)
data_file = os.path.join('../','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write("NumRooms, Alley , Price\n") #列名
    f.write("NA,Pave,127500\n")
    f.write("2,NA,106000\n")
    f.write("4,NA,178100\n")
    f.write("NA,NA,140000\n")

In [30]:
import pandas as pd

data = pd.read_csv(data_file)
data

NumRooms  Alley    Price
0       NaN    Pave  127500
1       2.0     NaN  106000
2       4.0     NaN  178100
3       NaN     NaN  140000

In [34]:
# 处理缺失数据
# iloc index of location
inputs,outputs = data.iloc[:,0:2],data.iloc[:,2]
inputs = inputs.fillna(inputs.mean()) #数值型
inputs = pd.get_dummies(inputs,dummy_na=True) # 将NA 看作一类
inputs

NumRooms   Alley _Pave   Alley _nan
0       3.0             1            0
1       2.0             0            1
2       4.0             0            1
3       3.0             0            1

In [35]:
# 转换成张量形式
import torch

X,y  = torch.tensor(inputs.values),torch.tensor(outputs.values)
X,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

线性代数

In [36]:
A = torch.arange(20).reshape((4,5))
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [37]:
A.T

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

In [38]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [40]:
B.T ==B #判断对称矩阵

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [41]:
# 创建任意轴的数据结构 :从外往里排
C= torch.arange(24).reshape((2,3,4))
C

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [43]:
# 相同形状计算
A = torch.arange(20,dtype=torch.float32).reshape((4,5))
B = A.clone() # 分配新内存，A的副本
A+B,B

(tensor([[ 0.,  2.,  4.,  6.,  8.],
         [10., 12., 14., 16., 18.],
         [20., 22., 24., 26., 28.],
         [30., 32., 34., 36., 38.]]),
 tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]))

In [44]:
A*B #哈德马积

tensor([[  0.,   1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.,  81.],
        [100., 121., 144., 169., 196.],
        [225., 256., 289., 324., 361.]])

In [49]:
a = 2
X = torch.arange(20,dtype=torch.float32).reshape((4,5))
X+a,(a*X).shape

(tensor([[ 2.,  3.,  4.,  5.,  6.],
         [ 7.,  8.,  9., 10., 11.],
         [12., 13., 14., 15., 16.],
         [17., 18., 19., 20., 21.]]),
 torch.Size([4, 5]))

In [50]:
# 计算元素和
X.sum()

tensor(190.)

In [54]:
# 任意形状求和
X = torch.arange(20*2,dtype=torch.float32).reshape((2,4,5))
sum_x= X.sum()
sum_x,sum_x.shape #标量

(tensor(780.), torch.Size([]))

In [55]:
sum_x0 = X.sum(axis=0)
sum_x0,sum_x0.shape  #第一轴没了

(tensor([[20., 22., 24., 26., 28.],
         [30., 32., 34., 36., 38.],
         [40., 42., 44., 46., 48.],
         [50., 52., 54., 56., 58.]]),
 torch.Size([4, 5]))

In [56]:
sum_x1 = X.sum(axis=1)
sum_x1,sum_x1.shape # 中间轴没了

(tensor([[ 30.,  34.,  38.,  42.,  46.],
         [110., 114., 118., 122., 126.]]),
 torch.Size([2, 5]))

In [57]:
sum_x2 = X.sum(axis=2)
sum_x2,sum_x2.shape #第三个轴没了

(tensor([[ 10.,  35.,  60.,  85.],
         [110., 135., 160., 185.]]),
 torch.Size([2, 4]))

In [58]:
sum_x01 = X.sum(axis=[0,1])
sum_x01,sum_x01.shape

(tensor([140., 148., 156., 164., 172.]), torch.Size([5]))

In [59]:
X.mean(),X.sum()/X.numel()

(tensor(19.5000), tensor(19.5000))

In [60]:
X.mean(axis=0),X.sum(axis=0)/X.shape[0]

(tensor([[10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.],
         [20., 21., 22., 23., 24.],
         [25., 26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.],
         [20., 21., 22., 23., 24.],
         [25., 26., 27., 28., 29.]]))

In [62]:
# 如果运算时不想降维(1d 2d 3d这种) 最后求和轴变为1而不是0
sum_X = X.sum(axis=1,keepdims=True)
sum_X
# 广播机制维度必须相同

tensor([[[ 30.,  34.,  38.,  42.,  46.]],

        [[110., 114., 118., 122., 126.]]])

In [63]:
X/sum_X

tensor([[[0.0000, 0.0294, 0.0526, 0.0714, 0.0870],
         [0.1667, 0.1765, 0.1842, 0.1905, 0.1957],
         [0.3333, 0.3235, 0.3158, 0.3095, 0.3043],
         [0.5000, 0.4706, 0.4474, 0.4286, 0.4130]],

        [[0.1818, 0.1842, 0.1864, 0.1885, 0.1905],
         [0.2273, 0.2281, 0.2288, 0.2295, 0.2302],
         [0.2727, 0.2719, 0.2712, 0.2705, 0.2698],
         [0.3182, 0.3158, 0.3136, 0.3115, 0.3095]]])

In [65]:
X

tensor([[[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]],

        [[20., 21., 22., 23., 24.],
         [25., 26., 27., 28., 29.],
         [30., 31., 32., 33., 34.],
         [35., 36., 37., 38., 39.]]])

In [69]:
X.cumsum(axis=1)
# 累计和

tensor([[[  0.,   1.,   2.,   3.,   4.],
         [  5.,   7.,   9.,  11.,  13.],
         [ 15.,  18.,  21.,  24.,  27.],
         [ 30.,  34.,  38.,  42.,  46.]],

        [[ 20.,  21.,  22.,  23.,  24.],
         [ 45.,  47.,  49.,  51.,  53.],
         [ 75.,  78.,  81.,  84.,  87.],
         [110., 114., 118., 122., 126.]]])

In [70]:
# 点积 按元素乘再求和
x = torch.arange(4,dtype=torch.float32)
y= torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [75]:
# 矩阵向量乘法 matric vector
A.T.shape,x.shape,torch.mv(A.T,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([70., 76., 82., 88., 94.]))

In [84]:
B=torch.ones((4,3))
A.T,torch.mm(A.T,B)

(tensor([[ 0.,  5., 10., 15.],
         [ 1.,  6., 11., 16.],
         [ 2.,  7., 12., 17.],
         [ 3.,  8., 13., 18.],
         [ 4.,  9., 14., 19.]]),
 tensor([[30., 30., 30.],
         [34., 34., 34.],
         [38., 38., 38.],
         [42., 42., 42.],
         [46., 46., 46.]]))

In [81]:
# L2范数
u = torch.tensor([3.0,-4.0])
u.norm()
# 平方和开根号

tensor(5.)

In [82]:
# L1范数
torch.abs(u).sum()

tensor(7.)

In [83]:
# 矩阵F范数
torch.norm(torch.ones((4,9)))
# 平方和开根号

tensor(6.)

- 梯度：分子布局符号 也可以规定分母布局
- 标量对列向量x的导数是行向量
- 梯度和等高线正交，变化最大的方向
- 列向量对标量的导数是列向量
- 列向量对列向量是矩阵
- 矩阵对标量不变
- 矩阵对向量求导，接到后面，分母总要转置

- 自动求导：区别于符号求导和数值求导
- 计算图：链式法则，正向积累，反向传播
- 先正向存储结果，然后反向计算，内存复杂度较高
- 关键是计算图的构造
  - 显示构造：定义好公式代入值
  - 隐式构造：记住数值，直接计算

In [90]:
import torch

In [91]:
# 存储梯度
x = torch.arange(4.0,requires_grad=True)
y = 2* torch.dot(x,x)
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [92]:
x.grad == 4*x

tensor([True, True, True, True])

In [93]:
# torch会积累梯度，所以清楚之前的值
x.grad.zero_()
x.grad

tensor([0., 0., 0., 0.])

In [94]:
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [106]:
# 深度学习中很少用向量来求导
x.grad.zero_()
y = x*x
y.sum().backward()
x.grad ==x*2

tensor([True, True, True, True])

In [107]:
# 某些计算移到计算图以外
x.grad.zero_()
u = y.detach()   #对系统来讲u不再是关于x的函数
z = u*x
z.sum().backward()
x.grad == u      #可以将某些参数固定住

tensor([True, True, True, True])

In [108]:
# 复杂的控制系统也可以解决
def f(a):
    b = a*2
    while b.norm()< 1000:
        b = b*2
    if b.sum()>0:
        c =b
    else:
        c = 100*b
    return c

a = torch.randn(size=(),requires_grad=True)
d = f(a)
d.backward()
a.grad == d/a

tensor(True)