In [ ]:
# beautiful soup对象：要解析的整个文档树 该方法支持遍历和搜索文档树等各种方法
# 1.1 创建beatifulsoup对象
import requests
from bs4 import BeautifulSoup
url = 'https://www.python123.io/ws/demo.html'
r = requests.get(url)
# print(r.content.decode()) 获取html内容
demo = r.text
soup = BeautifulSoup(demo, 'lxml')
# print(soup.prettify())
# html标签树 都是<p></p>表示的一对标签 标签内是属性域 属性由键值对构成
# 用BeautifulSoup类转化为字符串


In [ ]:
# 1.2 用字符串、变量和文件
soup = BeautifulSoup('<html>data</html>', 'lxml')
soup2 = BeautifulSoup(open('./learn.html'), 'lxml')
print(soup)

In [ ]:
print(soup2)

In [ ]:
# 1.3 beautifulsoup类的基本元素
# Tag<p></p>标签  p是标签的name 中间键值对是属性：<p>.attrs
# 标签内非属性部分：<p>.string  标签注释：comment
# 获得标签直接soup.p及其父标签
soup = BeautifulSoup(open('./learn.html'), 'lxml')
print(soup.title)
print(soup.a)
print(soup.a.name)
print(soup.a.parent.name)

In [ ]:
tag = soup.a
# 属性
print(tag.attrs)
print(tag.attrs['class'])
print(tag.attrs['href'])
print(type(tag))
print(type(tag.attrs))

In [ ]:
# 字符串
print(tag.string)
print(soup.p)
print(soup.p.string)
print(type(soup.p.string))
# NavigableString可以跨越标签查找里面的字符串

In [ ]:

# comment注释<!--data-->
newsoup = BeautifulSoup(
    "<b><!--This is a comment!--></b><p>\
    This is not a comment!</p>", 'lxml')
print(newsoup.b.string)
print(type(newsoup.b.string))
print(newsoup.p.string)
print(type(newsoup.p.string))


In [ ]:
# 2.1 html遍历方法之向下遍历
# .content将tag的所有结点存入列表
# .children迭代器用于循环遍历儿子节点
# .descendants 子孙节点迭代器用于循环遍历子孙节点
soup = BeautifulSoup(open('learn.html'),'lxml')
soup.head


In [ ]:
soup.head.contents

In [ ]:
soup.body.contents
# 换行符也属于节点

In [ ]:
soup.body.contents[1]
# 可以用for in  来进行遍历
for child in soup.body.contents:
    print(child)

In [ ]:
# 2.1 html遍历方法之向上遍历
# .parent  父亲标签
# .parents 先辈标签的迭代器
soup = BeautifulSoup(open('learn.html'),'lxml')
soup.title

In [ ]:
soup.title.parent

In [ ]:
soup.html.parent
# 最高的标签其父类就是自己

In [ ]:
soup.parent
# 无结果先辈是None

In [ ]:
# 遍历
for parent in soup.a.parents:
    if parent == None:
        print(parent)
    else:
        print(parent.name)

In [ ]:
# 2.3 平行遍历：同一父亲节点下
# .next_sibling 返回按照HTML文本顺序的下一个平行节点
# .previous_sibling 返回按照HTML文本顺序的上一个平行节点
# .next_siblings 迭代类型，返回按照HTML文本顺序的后续所有平行节点
# .previous_siblings 迭代器，返回按照HTML文本顺序的前续所有平行节点
url = 'https://www.python123.io/ws/demo.html'
r = requests.get(url)
demo = r.text
soup = BeautifulSoup(demo,'lxml')
soup.a.next_sibling
# 标签中的字符串也是节点

In [ ]:
soup.a.next_sibling.next_sibling

In [ ]:
soup.a.previous_sibling

In [ ]:
soup.a.previous_sibling.previous_sibling
# 没有前面的节点

In [ ]:
# 遍历a的后续平行节点
for tag in soup.a.next_siblings:
    if tag == None:
        print(tag)
    else:
        print(tag)

In [ ]:
# html格式化prettify()方法
print(soup)

In [ ]:
print(soup.prettify())
# 为每一个标签增加换行符，没化显示

In [ ]:
# 3.1 信息标记
# 标记后形成结构，用于展示、存储，利于程序的运用
# html是超文本标记语言
# xml/jsom/yaml
# xml是由html发展而来额 # 大多数信息是标签 internet
# json是有类型键值对 值可以是[];嵌套用{} 有双引号 适合程序处理
# 移动云端，接口，无注释
# yaml是无类型的键值对 ：无双引号 所属用缩进表示 并列用-号表示
# |表示整块数据 # 表示注释  可读性好 各类系统配置文件

In [ ]:
# 3.2 信息提取
# 1 完整解析信息的标记形式，在提取关键信息如bs4
# 过程繁琐，速度慢
# 2 直接搜索关键信息，缺乏准确性
# 结论：两种方法一起


In [45]:
# 提取html中的所有url地址
# 实现逻辑
# 1搜索到所有a标签
# 2解析a标签格式，提取href后的链接内容
print(soup.prettify())
for link in soup.find_all('a'):
    print(link.get('href'))   

<html>
 <head>
  <title>
   This is a python demo page
  </title>
 </head>
 <body>
  <p class="title">
   <b>
    The demo python introduces several python courses.
   </b>
  </p>
  <p class="course">
   Python is a wonderful general-purpose programming language. You can learn Python from novice to professional by tracking the following courses:
   <a class="py1" href="http://www.icourse163.org/course/BIT-268001" id="link1">
    Basic Python
   </a>
   and
   <a class="py2" href="http://www.icourse163.org/course/BIT-1001870001" id="link2">
    Advanced Python
   </a>
   .
  </p>
 </body>
</html>
http://www.icourse163.org/course/BIT-268001
http://www.icourse163.org/course/BIT-1001870001


In [46]:
# 3.3 soup对象的查找find_all
# find_all(name,attrs,recursive,string,**kwargs)
# name按名字检索
soup.find_all('a')

[<a class="py1" href="http://www.icourse163.org/course/BIT-268001" id="link1">Basic Python</a>,
 <a class="py2" href="http://www.icourse163.org/course/BIT-1001870001" id="link2">Advanced Python</a>]

In [47]:
# 同时查找多个标签应该列表传入，结果也是列表
soup.find_all(['a','b'])

[<b>The demo python introduces several python courses.</b>,
 <a class="py1" href="http://www.icourse163.org/course/BIT-268001" id="link1">Basic Python</a>,
 <a class="py2" href="http://www.icourse163.org/course/BIT-1001870001" id="link2">Advanced Python</a>]

In [48]:
# 给出的标签是True,查找所有标签
for link in soup.find_all(True):
    print(link.name)

html
head
title
body
p
b
p
a
a


In [49]:
# 所有以b开头的标签呢？正则表达式
import re
for tag in soup.find_all(re.compile('b')):
    print(tag.name)

body
b


In [50]:
# find_all(name,attrs,recursive,string,**kwargs)
# attrs某个标签中按属性检索,查找属性值为course的标签
soup.find_all('p',attrs='course')

[<p class="course">Python is a wonderful general-purpose programming language. You can learn Python from novice to professional by tracking the following courses:
 <a class="py1" href="http://www.icourse163.org/course/BIT-268001" id="link1">Basic Python</a> and <a class="py2" href="http://www.icourse163.org/course/BIT-1001870001" id="link2">Advanced Python</a>.</p>]

In [56]:
soup.find_all(id='link1')
# 包含在a标签中

[<a class="py1" href="http://www.icourse163.org/course/BIT-268001" id="link1">Basic Python</a>]

In [57]:
# 部分信息查找,对id进行正则
import re
soup.find_all(id=re.compile('link'))

[<a class="py1" href="http://www.icourse163.org/course/BIT-268001" id="link1">Basic Python</a>,
 <a class="py2" href="http://www.icourse163.org/course/BIT-1001870001" id="link2">Advanced Python</a>]

In [58]:
# find_all(name,attrs,recursive,string,**kwargs)
# recursive对儿子进行查找，是否对子孙全部检索，默认为TRUE
soup.find_all('a')

[<a class="py1" href="http://www.icourse163.org/course/BIT-268001" id="link1">Basic Python</a>,
 <a class="py2" href="http://www.icourse163.org/course/BIT-1001870001" id="link2">Advanced Python</a>]

In [59]:
soup.find_all('a',recursive=False)
# 只对儿子节点进行查找，不对子孙节点查找

[]

In [62]:
# find_all(name,attrs,recursive,string,**kwargs)
# string 对标签中间的字符串进行查找
print(soup.prettify())


<html>
 <head>
  <title>
   This is a python demo page
  </title>
 </head>
 <body>
  <p class="title">
   <b>
    The demo python introduces several python courses.
   </b>
  </p>
  <p class="course">
   Python is a wonderful general-purpose programming language. You can learn Python from novice to professional by tracking the following courses:
   <a class="py1" href="http://www.icourse163.org/course/BIT-268001" id="link1">
    Basic Python
   </a>
   and
   <a class="py2" href="http://www.icourse163.org/course/BIT-1001870001" id="link2">
    Advanced Python
   </a>
   .
  </p>
 </body>
</html>


In [63]:
soup.find_all(string='Basic Python')

['Basic Python']

In [64]:
# 对string进行re
import re
soup.find_all(string=re.compile('python'))

['This is a python demo page',
 'The demo python introduces several python courses.']

In [65]:
# find_all的简写
# <>()=tag.find_all()
# soup()=soup.find_all()
# 7种方法与find_all参数相同
# tag.find() 返回第一个结果字符串
# tag.find_parents() 从先辈中搜索，返回列表类型
# tag.find_parent() 返回一个结果字符串
# tag.find_next_siblings()后续平行节点，返回列表
# tag.find_next_sibling()后续平行节点，返回字符串 
# tag.find_previous_siblings()前续平行节点，返回列表
# tag.find_previous_sibling()前续平行节点，返回字符串   


In [17]:
import numpy as np
 
A = np.array([100,96,109,96,167,146,109,146,168]).reshape((3, 3))
B = np.array([123,125,189]).reshape((1, 3))
C = np.array([123,125,189]).reshape((3, 1))
print(A)
D = np.linalg.inv(A)
print(D)
E = np.dot(B,D)
F = float(np.dot(E,C))
print(F)
print((1/(1-F/252))/252)

[[100  96 109]
 [ 96 167 146]
 [109 146 168]]
[[ 0.03420052 -0.00108589 -0.02124593]
 [-0.00108589  0.02496029 -0.02098715]
 [-0.02124593 -0.02098715  0.03797578]]
251.11466816864828
1.1295199885371714


In [15]:
import numpy as np
 
A = np.array([100,123,109,123,252,189,109,189,168]).reshape((3, 3))
B = np.array([96,125,146]).reshape((1, 3))
C = np.array([96,125,146]).reshape((3, 1))
print(A)
D = np.linalg.inv(A)
print(D)
E = np.dot(B,D)
F = float(np.dot(E,C))
print(F)
print(1/(1-F/167)/167)

[[100 123 109]
 [123 252 189]
 [109 189 168]]
[[ 0.03415745 -0.00032531 -0.02179571]
 [-0.00032531  0.02539992 -0.02836385]
 [-0.02179571 -0.02836385  0.05200297]]
166.0990746764981
1.109969909729042


In [18]:
import numpy as np
 
A = np.array([100,123,96,123,252,125,96,125,167]).reshape((3, 3))
B = np.array([109,189,146]).reshape((1, 3))
C = np.array([109,189,146]).reshape((3, 1))
print(A)
D = np.linalg.inv(A)
print(D)
E = np.dot(B,D)
F = float(np.dot(E,C))
print(F)
print(1/(1-F/168)/168)

[[100 123  96]
 [123 252 125]
 [ 96 125 167]]
[[ 0.03532931 -0.01140435 -0.01177287]
 [-0.01140435  0.00999299 -0.00092399]
 [-0.01177287 -0.00092399  0.01344727]]
167.76703274693728
4.292448774896168


In [37]:
a = 123**2/100
print(a)
b = 252 - a
print(b/99)
c = b*1.12951999 
print(c)
print((1/c))

151.29
1.0172727272727273
113.7539581929
0.008790902891521672


In [32]:
a = 96**2/100
print(a)
b = 167 - a
print(b/99)
b*1.10996991

92.16
0.7559595959595959


83.0701480644

In [34]:
a = 109**2/100
print(a)
b = 168 - a
print(b/99)
b*4.29244877

118.81
0.49686868686868685


211.14555499629998

In [28]:
import numpy as np
 
A = np.array([100,0,0,0,0,100.71,6.92,54.93,0,6.92,74.84,41.36,0,54.93,41.36,49.19]).reshape((4,4))
print(A)
D = np.linalg.inv(A)
print(D)

[[100.     0.     0.     0.  ]
 [  0.   100.71   6.92  54.93]
 [  0.     6.92  74.84  41.36]
 [  0.    54.93  41.36  49.19]]
[[ 0.01        0.          0.          0.        ]
 [ 0.          1.12951999  1.10704112 -2.19214787]
 [ 0.          1.10704112  1.10996991 -2.16950853]
 [ 0.         -2.19214787 -2.16950853  4.29244877]]


In [ ]:
1.10996991*